[package]
name = "dino-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
config = "0.15.19"
crossterm = "0.29.0"
display-info = "0.5.7"
rand = "0.9.2"
rodio = "0.21.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
